name: example-environment
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - bqplot=0.12.30
  - scikit-learn
  - scipy
  - matplotlib
  - bqplot
  - openpyxl
  - yarn
  - ipywidgets >=5.2.2
  - traitlets >=4.3.0
  - traittypes >=0.0.6
  - numpy >=1.10.4,<2.0.0
  - pandas >=1.0.0,<2.0.0
  - bqscales  >=0.2.4,<0.3
  - scipy
  - jupyterlab
  - jupyter-packaging
  - pytest
  - nbval
  - pytest-cov
  - selenium
  - flake8
  - nose
  - codespell